BackendBundle\Entity\Almacen:
    type: entity
    table: almacen
    id:
        idAlmacen:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: id_almacen
            generator:
                strategy: IDENTITY
    fields:
        direccion:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
        referencia:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
    lifecycleCallbacks: {  }
